default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.20.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-black
    - mdformat-config
    - mdformat-gfm-alerts
    - mdformat-shfmt
    - mdformat-tables
    - mdformat-toc
- repo: local
  hooks:
  - id: commitlint-ci
    name: commitlint-ci
    stages: [manual]
    always_run: true
    language: node
    additional_dependencies: ['@commitlint/config-conventional']
    entry: bash
    args: ["-c", "npx commitlint --from $PRE_COMMIT_FROM_COMMIT --to $PRE_COMMIT_TO_COMMIT"]
    pass_filenames: false
