#!/bin/bash

echo $DEVCONTAINER_CACHE_BUILD_DEVCONTAINER_INITIALIZE | docker login ghcr.io --username $GITHUB_USER --password-stdin
export DEVCONTAINER_IMAGE=devcontainer-cache-build-devcontainer
export DEVCONTAINER_REGISTRY=ghcr.io/rcwbr
export DEVCONTAINER_DEFINITION_TYPE=bake
export DEVCONTAINER_INITIALIZE_PID=$PPID
export DEVCONTAINER_DEFINITION_FILES='devcontainer-bake.hcl useradd/devcontainer-bake.hcl pre-commit/devcontainer-bake.hcl cwd://.devcontainer/devcontainer-bake.hcl'
export DEVCONTAINER_BUILD_ADDITIONAL_ARGS='https://github.com/rcwbr/dockerfile-partials.git#2-define-pre-commit-dockerfile-partial'
curl https://raw.githubusercontent.com/rcwbr/devcontainer-cache-build/codespace-literate-robot-rpw7qgpp6wr2x9gq/initialize | bash
