on:
  workflow_call:
    inputs:
      build-context-user:
        description: The user name to set for the .devcontainer/initialize call
        default: "codespace"
        required: false
        type: string
      build-context-uid:
        description: The UID to set for the .devcontainer/initialize call
        default: 1000
        required: false
        type: number
      build-context-gid:
        description: The USER_GID to set for the .devcontainer/initialize call
        default: 1000
        required: false
        type: number
      devcontainer-cache-build-image-override:
        description: The image name to use to override the default devcontainer-cache-build image
        default: ""
        required: false
        type: string
      initialize-args:
        description: Args to provide to the initialize script, e.g. to configure user info
        default: ""
        required: false
        type: string
    outputs:
      devcontainer-cache-image-ref:
        description: "The reference of the devcontainer image built by the workflow"
        value: ${{ jobs.devcontainer-cache-build.outputs.devcontainer-cache-image-ref }}
      devcontainer-cache-image-config:
        description: "The Bake config of the (last layer of the) devcontainer image built by the workflow"
        value: ${{ jobs.devcontainer-cache-build.outputs.devcontainer-cache-image-config }}
      devcontainer-cache-image-all_configs:
        description: "The Bake configs of all layers of the devcontainer image built by the workflow"
        value: ${{ jobs.devcontainer-cache-build.outputs.devcontainer-cache-image-all_configs }}
jobs:
  devcontainer-cache-build:
    name: Populate devcontainer image cache
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: GHCR Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build devcontainer cache
        id: build-devcontainer-cache
        env:
          DEVCONTAINER_PUSH_IMAGE: true
          DEVCONTAINER_CACHE_BUILD_OVERRIDE_USER: ${{ inputs.build-context-user }}
          DEVCONTAINER_CACHE_BUILD_OVERRIDE_UID: ${{ inputs.build-context-uid }}
          DEVCONTAINER_CACHE_BUILD_OVERRIDE_USER_GID: ${{ inputs.build-context-gid }}
          DEVCONTAINER_CACHE_BUILD_IMAGE: ${{ inputs.devcontainer-cache-build-image-override }}
        run: |
          ./.devcontainer/initialize ${{ inputs.initialize-args }}
    outputs:
      devcontainer-cache-image-ref: ${{ steps.build-devcontainer-cache.outputs.ref }}
      devcontainer-cache-image-config: ${{ steps.build-devcontainer-cache.outputs.config }}
      devcontainer-cache-image-all_configs: ${{ steps.build-devcontainer-cache.outputs.all_configs }}
